apiVersion: v1
kind: PersistentVolume
metadata:
  name: pcap-pv
  labels:
    app: pcap-storage  # Add label for PVC selector
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: Directory
