apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcap-storage
  namespace: kubeflow-user-example-com  
spec:
  volumeName: pcap-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: pcap-storage
