"""
CLI to query the FAISS vector store generated by the data preparation pipeline.

Examples:
    # Text query
    python3 -m data_prep.query_vector_store \
        --index data_prep/vector_store.faiss \
        --query "UPF downlink routing issue ICMP request without reply" \
        --top-k 5

    # PCAP query (feature embedding), optional description for fusion
    python3 -m data_prep.query_vector_store \
        --index data_prep/vector_store.faiss \
        --pcap /path/to/new_capture.pcap \
        --description "Observed downlink failure after ICMP request" \
        --top-k 5
"""
import argparse
import json
from typing import Any, Dict, List
import numpy as np

from .embedding_generator import EmbeddingGenerator
from .vector_store import VectorStore
from .pcap_processor import PCAPProcessor


def format_result(metadata: Dict[str, Any]) -> str:
    parts: List[str] = []
    if 'file' in metadata:
        parts.append(f"file={metadata['file']}")
    if 'issue_type' in metadata:
        parts.append(f"issue_type={metadata['issue_type']}")
    if 'label' in metadata:
        parts.append(f"label={metadata['label']}")
    if 'description' in metadata:
        parts.append(f"description={metadata['description']}")
    return ", ".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="Query a FAISS vector store with text or a PCAP")
    parser.add_argument("--index", required=True, help="Path to the FAISS index file (e.g., data_prep/vector_store.faiss)")

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--query", help="Text query to embed and search for similar cases")
    group.add_argument("--pcap", help="Path to a PCAP to analyze and search similar cases")

    parser.add_argument("--description", help="Optional description to fuse with PCAP features (averaged)")
    parser.add_argument("--top-k", type=int, default=5, help="Number of nearest results to return (default: 5)")
    parser.add_argument("--model", type=str, default="all-MiniLM-L6-v2", help="SentenceTransformer model name (default: all-MiniLM-L6-v2)")
    parser.add_argument("--json", action="store_true", help="Output raw JSON results")
    parser.add_argument("--debug", action="store_true", help="Print debug info like feature text")

    args = parser.parse_args()

    # Load index
    store = VectorStore.load(args.index)

    # Build embedder
    embedder = EmbeddingGenerator(model_name=args.model)

    # Build query embedding from text or PCAP
    if args.query:
        query_embedding = embedder.generate_embedding(args.query)
        query_label = args.query
    else:
        # Extract features from PCAP and embed
        processor = PCAPProcessor()
        features = processor.process_pcap(args.pcap)
        feature_text = embedder._features_to_text(features)
        feature_embedding = embedder.generate_embedding(feature_text)

        if args.description:
            description_embedding = embedder.generate_embedding(args.description)
            query_embedding = (
                np.array(feature_embedding) + np.array(description_embedding)
            ) / 2.0
        else:
            query_embedding = np.array(feature_embedding)
        query_embedding = query_embedding.tolist()
        query_label = args.pcap
        if args.debug:
            print("\n[DEBUG] Query feature_text:")
            print(feature_text)

    # Search
    results = store.search(query_embedding, k=args.top_k)

    if args.json:
        as_json = [
            {"metadata": md, "distance": dist}
            for (md, dist) in results
        ]
        print(json.dumps(as_json, indent=2))
        return 0

    if not results:
        print("No results found (index may be empty).")
        return 0

    print(f"Top {min(args.top_k, len(results))} results for query: {query_label}")
    for rank, (metadata, distance) in enumerate(results, start=1):
        print(f"{rank}. distance={distance:.4f} | {format_result(metadata)}")
        if args.debug and 'feature_text' in metadata:
            print("    [DEBUG] matched feature_text:")
            print("    " + metadata['feature_text'])
    
    # Analysis and prediction
    if results:
        top_result = results[0]
        top_metadata, top_distance = top_result
        
        # Determine success/failure based on top match
        if top_metadata.get('label') == 0:
            status = "SUCCESS"
            confidence = "High" if top_distance < 0.3 else "Medium" if top_distance < 0.5 else "Low"
        else:
            status = "FAILURE"
            confidence = "High" if top_distance < 0.3 else "Medium" if top_distance < 0.5 else "Low"
        
        print(f"\n=== ANALYSIS RESULT ===")
        print(f"Status: {status}")
        print(f"Confidence: {confidence}")
        print(f"Issue Type: {top_metadata.get('issue_type', 'Unknown')}")
        print(f"Top Match: {top_metadata.get('file', 'Unknown')}")
        print(f"Distance Score: {top_distance:.4f}")
        
        if top_distance > 0.5:
            print("⚠️  Warning: Low confidence - consider reviewing manually")

    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
