# type: ignore
import json
import os

from pathlib import Path

import google.generativeai as genai
import numpy as np
import pandas as pd
import subprocess
from kubernetes import client, config
from typing import Optional, Dict, Any
from k8s_debug.common.utils import init_api_key
from mcp.server.fastmcp import FastMCP
from mcp.server.fastmcp.utilities.logging import get_logger


logger = get_logger(__name__)
AGENT_CARDS_DIR = 'agent_cards'
MODEL = 'models/embedding-001'

try:
    config.load_kube_config()
except Exception as e:
    raise Exception(f"Failed to load Kubernetes config: {str(e)}")

# Create Kubernetes API client
v1 = client.CoreV1Api()

def generate_embeddings(text):
    """Generates embeddings for the given text using Google Generative AI.

    Args:
        text: The input string for which to generate embeddings.

    Returns:
        A list of embeddings representing the input text.
    """
    return genai.embed_content(
        model=MODEL,
        content=text,
        task_type='retrieval_document',
    )['embedding']


def load_agent_cards():
    """Loads agent card data from JSON files within a specified directory.

    Returns:
        A list containing JSON data from an agent card file found in the specified directory.
        Returns an empty list if the directory is empty, contains no '.json' files,
        or if all '.json' files encounter errors during processing.
    """
    card_uris = []
    agent_cards = []
    dir_path = Path(AGENT_CARDS_DIR)
    if not dir_path.is_dir():
        logger.error(
            f'Agent cards directory not found or is not a directory: {AGENT_CARDS_DIR}'
        )
        return agent_cards

    logger.info(f'Loading agent cards from card repo: {AGENT_CARDS_DIR}')

    for filename in os.listdir(AGENT_CARDS_DIR):
        if filename.lower().endswith('.json'):
            file_path = dir_path / filename

            if file_path.is_file():
                logger.info(f'Reading file: {filename}')
                try:
                    with file_path.open('r', encoding='utf-8') as f:
                        data = json.load(f)
                        card_uris.append(
                            f'resource://agent_cards/{Path(filename).stem}'
                        )
                        agent_cards.append(data)
                except json.JSONDecodeError as jde:
                    logger.error(f'JSON Decoder Error {jde}')
                except OSError as e:
                    logger.error(f'Error reading file {filename}: {e}.')
                except Exception as e:
                    logger.error(
                        f'An unexpected error occurred processing {filename}: {e}',
                        exc_info=True,
                    )
    logger.info(
        f'Finished loading agent cards. Found {len(agent_cards)} cards.'
    )
    return card_uris, agent_cards


def build_agent_card_embeddings() -> pd.DataFrame:
    """Loads agent cards, generates embeddings for them, and returns a DataFrame.

    Returns:
        Optional[pd.DataFrame]: A Pandas DataFrame containing the original
        'agent_card' data and their corresponding 'Embeddings'. Returns None
        if no agent cards were loaded initially or if an exception occurred
        during the embedding generation process.
    """
    card_uris, agent_cards = load_agent_cards()
    logger.info('Generating Embeddings for agent cards')
    try:
        if agent_cards:
            df = pd.DataFrame(
                {'card_uri': card_uris, 'agent_card': agent_cards}
            )
            df['card_embeddings'] = df.apply(
                lambda row: generate_embeddings(json.dumps(row['agent_card'])),
                axis=1,
            )
            return df
        logger.info('Done generating embeddings for agent cards')
    except Exception as e:
        logger.error(f'An unexpected error occurred : {e}.', exc_info=True)
        return None


def serve(host, port, transport):  # noqa: PLR0915
    """Initializes and runs the Agent Cards MCP server.

    Args:
        host: The hostname or IP address to bind the server to.
        port: The port number to bind the server to.
        transport: The transport mechanism for the MCP server (e.g., 'stdio', 'sse').

    Raises:
        ValueError: If the 'GOOGLE_API_KEY' environment variable is not set.
    """
    init_api_key()
    logger.info('Starting Agent Cards MCP Server')
    mcp = FastMCP('agent-cards', host=host, port=port)

    df = build_agent_card_embeddings()

    @mcp.tool(
        name='find_agent',
        description='Finds the most relevant agent card based on a natural language query string.',
    )
    def find_agent(query: str) -> str:
        """Finds the most relevant agent card based on a query string.

        This function takes a user query, typically a natural language question or a task generated by an agent,
        generates its embedding, and compares it against the
        pre-computed embeddings of the loaded agent cards. It uses the dot
        product to measure similarity and identifies the agent card with the
        highest similarity score.

        Args:
            query: The natural language query string used to search for a
                   relevant agent.

        Returns:
            The json representing the agent card deemed most relevant
            to the input query based on embedding similarity.
        """
        logger.info(f'Finding agent for query {query}')
        query_embedding = genai.embed_content(
            model=MODEL, content=query, task_type='retrieval_query'
        )
        dot_products = np.dot(
            np.stack(df['card_embeddings']), query_embedding['embedding']
        )
        best_match_index = np.argmax(dot_products)
        logger.debug(
            f'Found best match at index {best_match_index} with score {dot_products[best_match_index]}'
        )
        return df.iloc[best_match_index]['agent_card']

    @mcp.resource('resource://agent_cards/list', mime_type='application/json')
    def get_agent_cards() -> dict:
        """Retrieves all loaded agent cards as a json / dictionary for the MCP resource endpoint.

        This function serves as the handler for the MCP resource identified by
        the URI 'resource://agent_cards/list'.

        Returns:
            A json / dictionary structured as {'agent_cards': [...]}, where the value is a
            list containing all the loaded agent card dictionaries. Returns
            {'agent_cards': []} if the data cannot be retrieved.
        """
        resources = {}
        logger.info('Starting read resources')
        resources['agent_cards'] = df['card_uri'].to_list()
        return resources

    @mcp.resource(
        'resource://agent_cards/{card_name}', mime_type='application/json'
    )
    def get_agent_card(card_name: str) -> dict:
        """Retrieves an agent card as a json / dictionary for the MCP resource endpoint.

        This function serves as the handler for the MCP resource identified by
        the URI 'resource://agent_cards/{card_name}'.

        Returns:
            A json / dictionary
        """
        logger.info(f'Starting read resource resource://agent_cards/{card_name}')
        resources = {}
        logger.info(
            f'Starting read resource resource://agent_cards/{card_name}'
        )
        resources['agent_card'] = (
            df.loc[
                df['card_uri'] == f'resource://agent_cards/{card_name}',
                'agent_card',
            ]
        ).to_list()

        return resources

    @mcp.tool()
    def get_pod_description(namespace: str, pod_name: str) -> Dict[str, Any]:
        """
        Get the description of a Kubernetes pod in YAML format.
        
        Args:
            namespace: The namespace of the pod
            pod_name: The name of the pod
            
        Returns:
            The pod description in YAML format
        """
        logger.info(f'Getting pod description for pod {pod_name} in namespace {namespace}')
        try:
            result = subprocess.run(
                ["kubectl", "get", "pod", pod_name, "-n", namespace, "-o", "yaml"],
                capture_output=True,
                text=True,
                check=True,
            )
            return {"yaml": result.stdout}
        except subprocess.CalledProcessError as e:
            return {"error": e.stderr}


    @mcp.tool()
    def get_pod_events(namespace: str, pod_name: str) -> Dict[str, Any]:
        """
        Get events related to a Kubernetes pod.
        
        Args:
            namespace: The namespace of the pod
            pod_name: The name of the pod
            
        Returns:
            The pod events
        """
        logger.info(f'Getting pod events for pod {pod_name} in namespace {namespace}')
        try:
            result = subprocess.run(
                [
                    "kubectl",
                    "get",
                    "events",
                    "-n",
                    namespace,
                    "--field-selector",
                    f"involvedObject.name={pod_name}",
                    "-o",
                    "json",
                ],
                capture_output=True,
                text=True,
                check=True,
            )
            return {"events": json.loads(result.stdout)}
        except subprocess.CalledProcessError as e:
            return {"error": e.stderr}
        except json.JSONDecodeError:
            return {"error": "Failed to parse JSON output from kubectl"}


    @mcp.tool()
    def get_pod_logs(
        namespace: str, pod_name: str, container_name: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Get logs from a Kubernetes pod.
        
        Args:
            namespace: The namespace of the pod
            pod_name: The name of the pod
            container_name: Optional name of the container in the pod
            
        Returns:
            The pod logs
        """
        logger.info(f'Getting pod logs for pod {pod_name} in namespace {namespace}')
        cmd = ["kubectl", "logs", pod_name, "-n", namespace]
        if container_name:
            cmd.extend(["-c", container_name])
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
            )
            return {"logs": result.stdout}
        except subprocess.CalledProcessError as e:
            return {"error": e.stderr}


    @mcp.tool()
    def list_pods(namespace: Optional[str] = None) -> Dict[str, Any]:
        """
        List all pods in a namespace.
        
        Args:
            namespace: The namespace to list pods from. If None, list all pods in all namespaces.
            
        Returns:
            List of pods in the namespace
        """
        logger.info(f'Listing pods in namespace {namespace}')
        try:
            if namespace is None:
               result = subprocess.run(
                ["kubectl", "get", "pods", "-A", "-o", "json"],
                capture_output=True,
                text=True,
                check=True,
            )
            else:
                result = subprocess.run(
                ["kubectl", "get", "pods", "-n", namespace, "-o", "json"],
                capture_output=True,
                text=True,
                check=True,
            )
            return {"pods": json.loads(result.stdout)}
        except subprocess.CalledProcessError as e:
            return {"error": e.stderr}
        except json.JSONDecodeError:
            return {"error": "Failed to parse JSON output from kubectl"}

    @mcp.tool()
    def list_namespaces() -> Dict[str, Any]:
        """
        List all namespaces.
        
        Returns:
            List of namespaces
        """
        logger.info(f'Listing namespaces')
        try:
            result = subprocess.run(
                ["kubectl", "get", "namespaces", "-o", "json"],
                capture_output=True,
                text=True,
                check=True,
            )
            return {"namespaces": json.loads(result.stdout)}
        except subprocess.CalledProcessError as e:
            return {"error": e.stderr}
        except json.JSONDecodeError:
            return {"error": "Failed to parse JSON output from kubectl"}

    @mcp.tool()
    def describe_node(node_name: str) -> Dict[str, Any]:
        """
        Get the description of a Kubernetes node.
    
        Args:
            node_name: The name of the node
        
        Returns:
            The node description
        """
        logger.info(f'Describing node {node_name}')
        try:
            result = subprocess.run(
                ["kubectl", "describe", "node", node_name],
                capture_output=True,
                text=True,
                check=True,
            )
            return {"description": result.stdout}
        except subprocess.CalledProcessError as e:
            return {"error": e.stderr}


    @mcp.tool()
    def get_resource_usage(namespace: str, pod_name: Optional[str] = None) -> Dict[str, Any]:
        """
        Get resource usage information for pods in a namespace.
    
        namespace: The namespace to get resource usage from
        pod_name: Optional name of a specific pod
        
        Returns:
            Resource usage information
        """
        logger.info(f'Getting resource usage for pod {pod_name} in namespace {namespace}')
        cmd = ["kubectl", "top", "pods", "-n", namespace]
        if pod_name:
            cmd.append(pod_name)
    
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
            )
            return {"usage": result.stdout}
        except subprocess.CalledProcessError as e:
            return {"error": e.stderr}

    
    
    @mcp.tool()
    def run_tcpdump(pod_name: str, container_name: str = None, namespace: str = "default", interface: str = "eth0", duration: int = 30, filter_expr: str = "") -> str:
        """     
        Run tcpdump in the specified container to capture network traffic
        Args:
            pod_name: The name of the pod
            container_name: The name of the container
            namespace: The namespace of the pod
            interface: Network interface to capture traffic on (default: eth0)
            duration: Duration in seconds to capture traffic (default: 30)
            filter_expr: Optional tcpdump filter expression
        """
        try:
            # Verify the pod exists
            try:
                pod = v1.read_namespaced_pod(name=pod_name, namespace=namespace)
            except client.exceptions.ApiException as e:
                if e.status == 404:
                    return f"Error: Pod '{pod_name}' not found in namespace '{namespace}'."
                else:
                    return f"Error accessing pod: {str(e)}"
            
            # Find the container to use
            selected_container = None
            if container_name:
                for container in pod.spec.containers:
                    if container.name == container_name:
                        selected_container = container.name
                        break
                if not selected_container:
                    return f"Error: Container '{container_name}' not found in pod '{pod_name}'."
            else:
                selected_container = pod.spec.containers[0].name
            # Check if tcpdump is available in the selected container
            check_cmd = ['/bin/sh', '-c', 'command -v tcpdump || echo "not found"']
            resp = v1.connect_get_namespaced_pod_exec(
                name=pod_name,
                namespace=namespace,
                container=selected_container,
                command=check_cmd,
                stderr=True,
                stdin=False,
                stdout=True,
                tty=False
            )
            
            if "not found" in resp:
                return f"Error: tcpdump is not available in container '{container_name}'. Please ensure the diagnostic tools are installed."
            
            # Build the tcpdump command
            output_file = f"/tmp/capture-{pod_name}-{int(time.time())}.pcap"
            filter_arg = f" '{filter_expr}'" if filter_expr else ""
            
            tcpdump_cmd = f"tcpdump -i {interface} -w {output_file} -G {duration} -W 1{filter_arg}"
            exec_command = ['/bin/sh', '-c', f"nohup {tcpdump_cmd} > /tmp/tcpdump.log 2>&1 &"]
            
            # Execute the command in the container
            v1.connect_get_namespaced_pod_exec(
                name=pod_name,
                namespace=namespace,
                container=selected_container,
                command=exec_command,
                stderr=True,
                stdin=False,
                stdout=True,
                tty=False
            )
            
            return f"Tcpdump started in pod '{pod_name}', container '{selected_container}'. Capturing traffic on interface '{interface}' for {duration} seconds. Output will be saved to {output_file}."
        
        except Exception as e:
            return f"Error running tcpdump: {str(e)}"

    @mcp.tool()
    def run_dns_tool(pod_name: str, container_name: str = None, namespace: str = "default", target: str = "kubernetes.default.svc.cluster.local", query_type: str = "A") -> str:
        """     
        Run DNS lookup tools in the specified container
        Args:
            pod_name: The name of the pod
            container_name: The name of the container
            namespace: The namespace of the pod
            target: DNS name to query (default: kubernetes.default.svc.cluster.local)
            query_type: DNS query type (A, AAAA, MX, etc.) (default: A)
        """
        try:
            # Verify the pod exists
            try:
                pod = v1.read_namespaced_pod(name=pod_name, namespace=namespace)
            except client.exceptions.ApiException as e:
                if e.status == 404:
                    return f"Error: Pod '{pod_name}' not found in namespace '{namespace}'."
                else:
                    return f"Error accessing pod: {str(e)}"
            
            # Find the container to use
            selected_container = None
            if container_name:
                for container in pod.spec.containers:
                    if container.name == container_name:
                        selected_container = container.name
                        break
                if not selected_container:
                    return f"Error: Container '{container_name}' not found in pod '{pod_name}'."
            else:
                # Fallback to first container in the pod
                selected_container = pod.spec.containers[0].name
            
            # Check if DNS tools are available
            dns_tools = {
                "dig": False,
                "nslookup": False
            }
            
            for tool in dns_tools:
                check_cmd = ['/bin/sh', '-c', f'command -v {tool} || echo "not found"']
                resp = v1.connect_get_namespaced_pod_exec(
                    name=pod_name,
                    namespace=namespace,
                    container=selected_container,
                    command=check_cmd,
                    stderr=True,
                    stdin=False,
                    stdout=True,
                    tty=False
                )
                
                if "not found" not in resp:
                    dns_tools[tool] = True
            
            if not any(dns_tools.values()):
                return f"Error: No DNS tools (dig, nslookup) are available in container '{selected_container}'. Please ensure the diagnostic tools are installed."
            
            # Run available DNS lookup commands
            results = []
            
            # Add resolv.conf check
            try:
                resolv_cmd = ['/bin/sh', '-c', 'cat /etc/resolv.conf']
                resp = v1.connect_get_namespaced_pod_exec(
                    name=pod_name,
                    namespace=namespace,
                    container=selected_container,
                    command=resolv_cmd,
                    stderr=True,
                    stdin=False,
                    stdout=True,
                    tty=False
                )
                results.append(f"DNS Configuration (/etc/resolv.conf):\n{resp}\n")
            except Exception:
                results.append("Could not read DNS configuration (/etc/resolv.conf)\n")
            
            # Run dig if available
            if dns_tools["dig"]:
                dig_cmd = ['/bin/sh', '-c', f'dig {target} {query_type}']
                try:
                    resp = v1.connect_get_namespaced_pod_exec(
                        name=pod_name,
                        namespace=namespace,
                        container=selected_container,
                        command=dig_cmd,
                        stderr=True,
                        stdin=False,
                        stdout=True,
                        tty=False
                    )
                    results.append(f"Dig Results:\n{resp}\n")
                except Exception as e:
                    results.append(f"Error running dig: {str(e)}\n")
            
            # Run nslookup if available
            if dns_tools["nslookup"]:
                nslookup_cmd = ['/bin/sh', '-c', f'nslookup -type={query_type} {target}']
                try:
                    resp = v1.connect_get_namespaced_pod_exec(
                        name=pod_name,
                        namespace=namespace,
                        container=selected_container,
                        command=nslookup_cmd,
                        stderr=True,
                        stdin=False,
                        stdout=True,
                        tty=False
                    )
                    results.append(f"Nslookup Results:\n{resp}\n")
                except Exception as e:
                    results.append(f"Error running nslookup: {str(e)}\n")
            
            return "\n".join(results)
        
        except Exception as e:
            return f"Error running DNS tools: {str(e)}"

    @mcp.tool()
    def collect_diagnostic_data(pod_name: str, container_name: str = None, namespace: str = "default") -> str:
        """     
        Collect comprehensive diagnostic data from the specified container
        Args:
            pod_name: The name of the pod
            container_name: The name of the container
            namespace: The namespace of the pod
        """
        try:
            # Verify the pod exists
            try:
                pod = v1.read_namespaced_pod(name=pod_name, namespace=namespace)
            except client.exceptions.ApiException as e:
                if e.status == 404:
                    return f"Error: Pod '{pod_name}' not found in namespace '{namespace}'."
                else:
                    return f"Error accessing pod: {str(e)}"
            
            # Find the container to use
            selected_container = None
            if container_name:
                for container in pod.spec.containers:
                    if container.name == container_name:
                        selected_container = container.name
                        break
                if not selected_container:
                    return f"Error: Container '{container_name}' not found in pod '{pod_name}'."
            else:
                selected_container = pod.spec.containers[0].name
            # Create a directory for diagnostic data
            timestamp = int(time.time())
            diagnostic_dir = f"/tmp/diagnostic-{pod_name}-{timestamp}"
            mkdir_cmd = ['/bin/sh', '-c', f"mkdir -p {diagnostic_dir}"]
            v1.connect_get_namespaced_pod_exec(
                name=pod_name,
                namespace=namespace,
                container=selected_container,
                command=mkdir_cmd,
                stderr=True,
                stdin=False,
                stdout=True,
                tty=False
            )
            
            # Collect diagnostic data
            diagnostic_files = []
            
            # Define diagnostic commands to run
            diagnostic_commands = {
                # Network diagnostics
                "netstat": f"netstat -tunapl > {diagnostic_dir}/netstat.txt 2>/dev/null || echo 'netstat not available' > {diagnostic_dir}/netstat.txt",
                "ip_addr": f"ip addr > {diagnostic_dir}/ip-addr.txt 2>/dev/null || echo 'ip addr not available' > {diagnostic_dir}/ip-addr.txt",
                "ip_route": f"ip route > {diagnostic_dir}/ip-route.txt 2>/dev/null || echo 'ip route not available' > {diagnostic_dir}/ip-route.txt",
                "dns_config": f"cat /etc/resolv.conf > {diagnostic_dir}/resolv.conf.txt 2>/dev/null || echo 'resolv.conf not available' > {diagnostic_dir}/resolv.conf.txt",
                
                # System diagnostics
                "processes": f"ps aux > {diagnostic_dir}/processes.txt 2>/dev/null || echo 'ps not available' > {diagnostic_dir}/processes.txt",
                "memory": f"free -m > {diagnostic_dir}/memory.txt 2>/dev/null || echo 'free not available' > {diagnostic_dir}/memory.txt",
                "disk": f"df -h > {diagnostic_dir}/disk-usage.txt 2>/dev/null || echo 'df not available' > {diagnostic_dir}/disk-usage.txt",
                "env_vars": f"env > {diagnostic_dir}/environment.txt 2>/dev/null || echo 'env not available' > {diagnostic_dir}/environment.txt"
            }
            
            # Execute each diagnostic command
            for name, cmd in diagnostic_commands.items():
                try:
                    exec_cmd = ['/bin/sh', '-c', cmd]
                    v1.connect_get_namespaced_pod_exec(
                        name=pod_name,
                        namespace=namespace,
                        container=selected_container,
                        command=exec_cmd,
                        stderr=True,
                        stdin=False,
                        stdout=True,
                        tty=False
                    )
                    diagnostic_files.append(name)
                except Exception:
                    # Continue with other commands if one fails
                    pass
            
            # Get container logs
            try:
                logs = v1.read_namespaced_pod_log(
                    name=pod_name,
                    namespace=namespace,
                    container=selected_container,
                    tail_lines=1000
                )
                
                log_file = f"{diagnostic_dir}/container-logs.txt"
                write_cmd = ['/bin/sh', '-c', f"cat > {log_file} << 'EOL'\n{logs}\nEOL"]
                v1.connect_get_namespaced_pod_exec(
                    name=pod_name,
                    namespace=namespace,
                    container=selected_container,
                    command=write_cmd,
                    stderr=True,
                    stdin=False,
                    stdout=True,
                    tty=False
                )
                diagnostic_files.append("container-logs")
            except Exception:
                # Continue if logs can't be collected
                pass
            
            # Create a summary file
            summary = f"Diagnostic data collected at {timestamp}\n"
            summary += f"Pod: {pod_name}\n"
            summary += f"Container: {container_name}\n"
            summary += f"Namespace: {namespace}\n"
            summary += "Files collected:\n"
            for file in diagnostic_files:
                summary += f"- {file}\n"
            
            summary_file = f"{diagnostic_dir}/summary.txt"
            write_summary_cmd = ['/bin/sh', '-c', f"cat > {summary_file} << 'EOL'\n{summary}\nEOL"]
            v1.connect_get_namespaced_pod_exec(
                name=pod_name,
                namespace=namespace,
                container=selected_container,
                command=write_summary_cmd,
                stderr=True,
                stdin=False,
                stdout=True,
                tty=False
            )
            
            return f"Diagnostic data collected and saved to {diagnostic_dir}\n{summary}"
        
        except Exception as e:
            return f"Error collecting diagnostic data: {str(e)}"
      
    
    logger.info(
        f'Agent cards MCP Server at {host}:{port} and transport {transport}'
    )
    mcp.run(transport=transport)